# Generated by Django 5.2.9 on 2025-12-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/properties/'),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
