# Generated by Django 5.2.9 on 2025-12-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_image_delete_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
