# Generated by Django 5.2.9 on 2026-01-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_night',
            new_name='number_of_nights',
        ),
    ]
